// GENERATED: 2011-04-06 18:05:29 -0700
// This file is automatically generated by spade.  To update run 
// 'spade update'. To use this file, reference it in your HTML file.  Base 
// sure that your base URL is to the top level directory containing all of 
// your files.

/*globals spade */
//@ begin boot
(function() {
  // load spade itself
  var script = document.createElement('script');
  script.src = ".spade/boot/spade.js";
  script.onload = function() {

    // Register remaining packages with spade
spade.register("ivory", {
  "name": "ivory",
  "author": "Charles Jolley",
  "version": "0.0.1",
  "summary": "Node APIs for Spade",
  "description": "Partial implementation of the node.js APIs built on top of spade",
  "homepage": "http://ivory-js.com",
  "directories": {
    "lib": "./lib"
  },
  "root": ".",
  "sync": true,
  "files": [
    "ivory-0.0.1/lib/buffer.js",
    "ivory-0.0.1/lib/events.js",
    "ivory-0.0.1/lib/fs.js",
    "ivory-0.0.1/lib/main.js",
    "ivory-0.0.1/lib/path.js",
    "ivory-0.0.1/lib/ruby/buffer.rb",
    "ivory-0.0.1/lib/ruby/constants.rb",
    "ivory-0.0.1/lib/ruby/events.rb",
    "ivory-0.0.1/lib/ruby/fs.rb",
    "ivory-0.0.1/lib/ruby/process.rb",
    "ivory-0.0.1/lib/stream.js",
    "ivory-0.0.1/lib/util.js",
    "ivory-0.0.1/package.json",
    "ivory-0.0.1.spd",
    "lib/buffer.js",
    "lib/events.js",
    "lib/fs.js",
    "lib/main.js",
    "lib/path.js",
    "lib/ruby/buffer.rb",
    "lib/ruby/constants.rb",
    "lib/ruby/events.rb",
    "lib/ruby/fs.rb",
    "lib/ruby/process.rb",
    "lib/stream.js",
    "lib/util.js",
    "LICENSE.txt",
    "README.md"
  ]
});


    // find the main module to run
    var main = null;
    var scripts = document.scripts || document.getElementsByTagName("script"),
        len = scripts.length;
    for(var idx=0;!main && idx<len;idx++) {
      main = scripts[idx].getAttribute('data-require');
    }
    scripts = null; // avoid memory leaks in IE

    if (main) spade.ready(function() { spade.require(main); });
  };

  var head = document.head || document.body || document;
  head.appendChild(script);

  script = head = null; // avoid memory leaks in IE
})();
//@ end boot
