require 'libgems/installer'

module LibGems
  class Installer

    def app_script_text(bin_file_name)
      <<-TEXT
#{shebang bin_file_name}
#
# This file was generated by BPM.
#
# The application '#{@spec.name}' is installed as part of an bpkg, and
# this file is here to facilitate running it.
#

version = "#{LibGems::Requirement.default}"

if ARGV.first =~ /^_(.*)_$/ and LibGems::Version.correct? $1 then
  version = $1
  ARGV.shift
end

gem '#{@spec.name}', version

path = LibGems.bin_path('#{@spec.name}', '#{bin_file_name}', version)
shebang = File.open(path){|f| f.readline }

if shebang =~ /^\#\!.*ruby/
  load path
else
  exec path, *ARGV
end
TEXT
    end

  end
end


